export const TEXT = {
  NAME: 'RFPgenius',
  COMMON: {
    VIEW: 'Click to View',
    REMOVE: 'Remove',
    CANCEL: 'Cancel',
    CLOSE: 'Close',
  },
  NAVBAR: {
    DASHBOARD: 'Dashboard',
    VENDORS: 'Vendors',
    CREATE_RFP: 'Create RFP',
    PROPOSALS: 'Proposal',
  },
  DASHBOARD: {
    HEADING: 'Dashboard',
    SUB_HEADING: 'Overview of activity, proposals, and system insights.',
    CARD_ONE_HEADING: 'RFPs Created',
    CARD_TWO_HEADING: 'Proposals Received',
    CARD_THIRD_HEADING: 'Vendors Added',
    ACTIVITY_TITLE: 'Recent Activity',
    HISTORY_TITLE: 'History',
    NO_HISTORY: 'No History',
  },
  VENDORS: {
    HEADING: 'Vendors',
    SUB_HEADING: 'Manage all vendors you send RFPs to.',
    SEARCH: "Search vendor's name...",
    ADD_VENDOR: '+ Add Vendor',
    ADD_NEW_VENDOR: 'Add New Vendor',
    SAVE: 'Save Vendor',
    NAME_PLACEHOLDER: "Vendor's Name",
    EMAIL_PLACEHOLDER: 'Email Address',
    CATEGORY_PLACEHOLDER: 'Category',
  },
  CREATE_RFP: {
    HEADING: 'Create RFP',
    SUB_HEADING: 'Describe your requirement — AI will generate a structured RFP.',
    REQUIREMENT: 'Your Requirement',
    DOMAIN: 'Domain:',
    CHOOSE_DOMAIN: 'Choose Domain',
    WRITE_PROMPT_PLACEHOLDER: 'Describe your requirement...',
    GENERATE: 'Generate RFP',
    PROPOSAL_HEADING: 'Structured Proposal',
    GET_PROPOSAL_TEXT: 'AI-generated proposal will appear here...',
    PROPOSAL_REQUIREMENTS: 'Requirements',
    PROPOSAL_BUDGET: 'Budget',
    PROPOSAL_DELIVERY: 'Delivery Timeline',
    PROPOSAL_PAYMENT_TERMS: 'Payment Terms',
    PROPOSAL_WARRANTY: 'Warranty',
    VENDORS_AVAILABLE: 'Available Vendors',
    SEND_PROPOSAL: 'Send to Vendors',
  },
  PROPOSAL: {
    HEADING: 'All RFP Proposals',
    BTN_TEXT: 'View Proposal',
  },
  PROPOSAL_DETAILS: {
    HEADING: 'Proposals',
    SUB_HEADING: 'AI analyzed proposals received for this RFP.',
    CARD_HEADING: 'Proposals for This Request',
    CARD_SUB_HEADING: 'Below are all proposals received from vendors.',
    TOTAL_REPLIES: 'Total Replies:',
    ALL_PROPOSAL: 'All Vendor Proposals',
    SCORE: 'Score:',
    SUMMARY: 'Summary:',
    REPLY: 'Reply:',
    BEST_PROPOSAL: 'RFPGenius — Best Proposal',
    HIGHEST_SCORE: 'This vendor scored the highest.',
  },
  HISTORY_DETAIL: {
    RFP_DETAILS: 'RFP Details',
    NO_DETAILS: 'No details available',
  },
  SELECT_TEMPLATE: {
    SELECT_TEMPLATE: 'Select RFP Template',
  },
};
